### ISSUE TITLE
header 모바일버전

### ISSUE THREAD

**Issue by syeon2565** [mju-likelion/mission24-team3-frontend#28]
- 현재 header 모바일 버전 깨짐 현상 해결
<img width="254" alt="스크린샷 2023-01-04 오후 10 53 01" src="https://user-images.githubusercontent.com/73578701/210569882-36fe8ef6-e932-4a31-9d11-28d3ad99d958.png">

**Comment by yuraup** [comment]
로그인 회원가입은 모바일에서 navbar에 있는 걸로 디자인 되어 있는데 
모바일에서도 데스크탑 버전처럼 헤더에 로그인/회원가입이 위치하는 게 더 좋을 것 같으신가요? 
현재 디자인을 수정할지 아니면 모바일 디자인 그대로 구현할지 의견 필요해보입니다!

<img width="230" alt="image" src="https://user-images.githubusercontent.com/81766889/213143816-5041aba5-0d62-45e0-8f72-27aa8bae0f00.png">
