### ISSUE TITLE
Footer 문의창구

### ISSUE THREAD

**Issue by syeon2565** [mju-likelion/mission24-team3-frontend#31]
- 멋쟁이사자처럼 10기 활동종료로 인한 참여자들 문의창구 어떻게 할 것인지 논의 필요

**Comment by yuraup** [comment]
홍보 겸 피드백 반영용으로 잘챙기짐 인스타 계정을 생성하는 것도 나쁘지 않을 것 같습니다! 
이메일은 어떻게 해야 할지 고민됩니다. 좋은 의견 있으신 분 있으실까요?

**Comment by syeon2565** [comment]
계정을 만든다면 아이디는 저희 도메인처럼 pack.recipes가 좋아보이고, 그럼 이게 관리다 되어야하는데, 그게 가능할까요?
홍보 겸 만든다면 사실 팔로워 수가 중요할 것 같아가지구요!

**Comment by yuraup** [comment]
인스타 관리는 어렵지 않을 것 같긴 해요. 팔로워 수가 중요하다는 건 동감합니다. ㅠㅠ 
홍보를 간략히 할 거라면 그냥 저희끼리 링크 보내주고 하는 걸로 끝내고 괜찮을 것 같고,
제대로 해 볼 생각이라면 인스타 계정을 파는 게 나을 것 같아요!
