### ISSUE TITLE
og 적용 및 타이틀 수정

### ISSUE THREAD

**Issue by syeon2565** [mju-likelion/mission24-team3-frontend#33]
- Title이 React App으로 보입니다.
- OG적용도 필요해보입니다.

**Comment by yuraup** [comment]
og 이미지 22일까지 만들어 두겠습니다!

**Comment by syeon2565** [comment]
저희 파비콘 이미지도 필요로해서 이 디자인도 만들어져야할 것 같아요

**Comment by yuraup** [comment]
파비콘 일단 해 둔 걸로 올려뒀는데, 다른 작업들 다 마무리되면 파비콘도 다시 디자인해서 수정하겠습니다!
