### ISSUE TITLE
드래그 방지 css 추가 

### ISSUE THREAD

**Issue by yuraup** [mju-likelion/mission24-team3-frontend#37]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/81766889/213142095-da96011e-c6a2-47a8-b872-d6bff6af8592.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/81766889/213142228-d584d558-a76b-4068-9786-4e83534907ae.png">

<img width="114" alt="image" src="https://user-images.githubusercontent.com/81766889/213142266-b226fb20-4c81-4b62-89a7-a6e1116d2de2.png">

<img width="479" alt="image" src="https://user-images.githubusercontent.com/81766889/213142334-a924d1d2-656a-4831-92b4-e262f24f4829.png">

<img width="224" alt="image" src="https://user-images.githubusercontent.com/81766889/213142366-9b53e4e1-0298-4ec5-b296-a2235e0c2e6f.png">

<img width="506" alt="image" src="https://user-images.githubusercontent.com/81766889/213142411-cb5ceb68-44e7-49c5-8919-0932c9a586a4.png">

**Comment by syeon2565** [comment]
드래그 방지가 필요한 작업인가요?
다른 곳을 봐도 드래그는 되는 것 같아서요!

**Comment by yuraup** [comment]
다시 생각해 봤는데, 성연님 말씀도 일리가 있다고 생각해서 드롭다운 네브바의 버튼만 드래그 방지 css 추가하고 리스트는 드래그 방지 추가하지 않겠습니다
